# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Optional
from datetime import date, datetime
from typing_extensions import Literal

from ..._models import BaseModel
from .ai_content import AIContent

__all__ = ["VehicleDetail"]


class VehicleDetail(BaseModel):
    """Full vehicle resource.

    Returned by `GET /v1/dealers/{id}/vehicles/{id}`,
    `POST /v1/dealers/{id}/vehicles`, and `PATCH /v1/dealers/{id}/vehicles/{id}`.

    Carries three layers of information:

    * **Partner-supplied** — what the partner posted (``plate``, ``description``,
      ``sale_price_eur``, etc.).
    * **Catalogue-derived** — ``technical_details`` is a flat dictionary of
      Motornet-backed technical attributes using Italian domain labels such as
      ``cilindrata``, ``kw``, ``hp``, ``lunghezza``, ``consumo_medio``, and
      ``emissioni_co2``.
    * **AI-derived** — ``ai_content`` carries the editorial output the
      cross-network consumers display (descriptions, highlights, FAQ,
      SEO meta). ``null`` until the worker has processed the vehicle.

    Dealer-entered inventory, commercial, condition, service-history, catalogue,
    media, and AI-derived fields are available through the SDK so partners can
    keep the same stock record DealerMax shows.
    """

    certified_km: int

    created_at: datetime

    dealer_id: str

    description: str

    enabled_channels: List[Literal["rewind", "nos"]]

    extended_warranty_enabled: bool

    is_visible: bool

    last_modified_at: datetime

    motornet_code: str

    partner_id: str

    plate: str

    registration_year: int

    sale_price_eur: float

    vat_displayed: bool

    vehicle_id: str

    ai_content: Optional[AIContent] = None
    """Editorial content generated by the partnermax AI pipeline.

    `null` immediately after `POST` until the worker has produced the row (≤ 60
    seconds). Populated for the same consumer-AI surfaces (MCP, Custom GPT, NLWeb).
    """

    ai_short: Optional[str] = None

    ai_tagline: Optional[str] = None

    alloy_wheel_size: Optional[int] = None

    base_color: Optional[str] = None

    brand: Optional[str] = None

    co2_emissions_g_km_override: Optional[float] = None

    color: Optional[str] = None

    cost_price_eur: Optional[float] = None

    cover_image_url: Optional[str] = None

    damage_repaired: Optional[bool] = None

    deleted_at: Optional[datetime] = None

    double_keys_available: Optional[bool] = None

    extended_warranty_months: Optional[int] = None

    fuel_type: Optional[str] = None

    fuel_type_override: Optional[str] = None

    image_count: Optional[int] = None

    image_urls: Optional[List[str]] = None
    """Vehicle photos in display order.

    The first entry is the cover photo (`position=1` in the dedicated images
    endpoint).
    """

    inspection_due_date: Optional[date] = None

    last_inspection_date: Optional[date] = None

    last_inspection_km: Optional[int] = None

    last_service_date: Optional[date] = None

    last_service_km: Optional[int] = None

    last_service_notes: Optional[str] = None

    model: Optional[str] = None

    notes: Optional[str] = None

    ownership_transfer_date: Optional[date] = None

    power_kw_override: Optional[int] = None

    previous_owner_count: Optional[int] = None

    property_tax_due_date: Optional[date] = None

    registration_month: Optional[int] = None

    service_history_available: Optional[bool] = None

    technical_details: Optional[Dict[str, object]] = None
    """Flat dictionary of Motornet-backed technical attributes for this
    `motornet_code`.

    Keys stay in Italian domain vocabulary; native units are preserved (mm, kg, kW,
    CV, g/km, etc.).
    """

    trim: Optional[str] = None

    trim_alias: Optional[str] = None

    vehicle_damaged: Optional[bool] = None

    vin: Optional[str] = None

    wltp_consumption_combined_l_100km: Optional[float] = None

    wltp_consumption_extraurban_l_100km: Optional[float] = None

    wltp_consumption_urban_l_100km: Optional[float] = None
