# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Optional
from datetime import datetime

from ..._models import BaseModel
from .ai_content import AIContent

__all__ = ["VehicleDetail"]


class VehicleDetail(BaseModel):
    """Full vehicle resource.

    Returned by `GET /v1/dealers/{id}/vehicles/{id}`,
    `POST /v1/dealers/{id}/vehicles`, and `PATCH /v1/dealers/{id}/vehicles/{id}`.

    Carries three layers of information:

    * **Partner-supplied** — what the partner posted (``plate``, ``description``,
      ``sale_price_eur``, etc.).
    * **Catalogue-derived** — ``technical_details`` is the flat
      ``mnet_dettagli_usato`` dict (Italian column keys: ``cilindrata``, ``kw``,
      ``hp``, ``lunghezza``, ``consumo_medio``, ``emissioni_co2``, etc.).
      Same shape conventions as ``NltOfferDetail`` per
      ``feedback_partnermax_field_naming_us_english``.
    * **AI-derived** — ``ai_content`` carries the editorial output the
      cross-network consumers display (descriptions, highlights, FAQ,
      SEO meta). ``null`` until the worker has processed the vehicle.

    Fields the partner does NOT see through this surface (because they
    are dealer-internal margin/operations data the partner does not own):
    ``cost_price_eur``, ``inspection_expiry_date``, ``road_tax_expiry_date``,
    ``previous_owner_count``, ``previous_ownership_transfer_date``,
    ``last_service_*``. These exist in the underlying DB tables for the
    DealerMAX dashboard but are intentionally not exposed via the SDK.
    """

    certified_km: int

    created_at: datetime

    dealer_id: str

    description: str

    extended_warranty_enabled: bool

    is_for_sale: bool

    is_visible: bool

    last_modified_at: datetime

    motornet_code: str

    partner_id: str

    plate: str

    registration_year: int

    sale_price_eur: float

    vat_displayed: bool

    vehicle_damaged: bool

    vehicle_id: str

    ai_content: Optional[AIContent] = None
    """Editorial content generated by the partnermax AI pipeline.

    `null` immediately after `POST` until the worker has produced the row (≤ 60
    seconds). Populated for the same consumer-AI surfaces (MCP, Custom GPT, NLWeb).
    """

    alloy_wheel_size: Optional[int] = None

    brand: Optional[str] = None

    color: Optional[str] = None

    extended_warranty_months: Optional[int] = None

    fuel_type: Optional[str] = None

    image_urls: Optional[List[str]] = None
    """Vehicle photos in display order.

    The first entry is the cover photo (`position=1` in the dedicated images
    endpoint).
    """

    model: Optional[str] = None

    notes: Optional[str] = None

    registration_month: Optional[int] = None

    technical_details: Optional[Dict[str, object]] = None
    """
    Flat dict of every non-null `mnet_dettagli_usato` column for this
    `motornet_code`. Keys stay in Italian because they are raw SQL column names;
    native units preserved (mm, kg, kW, CV, g/km, etc.).
    """

    trim: Optional[str] = None

    vin: Optional[str] = None
